# Generated by Django 4.2.7 on 2025-08-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_mfa_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="backup_codes",
        ),
        migrations.RemoveField(
            model_name="user",
            name="mfa_enabled",
        ),
        migrations.RemoveField(
            model_name="user",
            name="mfa_secret",
        ),
    ]
